### ISSUE TITLE
su-exec: setgroups: Operation not permitted when `user: krakend`

### ISSUE THREAD

**Issue by amir-ziaei** [krakendio/docker-library#2]
When I pass `user:krakend` to container like follows:
```
// docker-compose.yml
version: '3.7'
services:
  krakend-agw:
    image: devopsfaith/krakend
    ports:
      - 8081:8080
    volumes:
      - ./infrastructure/krakend-config:/etc/krakend/
    command: run --config /etc/krakend/krakend.json
    user: krakend
```

It works fine and my container starts as `krakend` user. But on some other machines we get the following error on start:
```
su-exec: setgroups: Operation not permitted
```

Am I not supposed to set the user? Why does it work on some machines only?
